### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Warfare#1]
Ahoy!
Ive seen you mention this plugin in the comments to other issues, from the name of the plugin I would take a guess at maybe siege additions? 

Im super interested!

**Comment by TylerS1066** [comment]
The first priority with this plugin is to help reduce the number of features found in Movecraft itself such that it is simpler to setup, easier to update, and easier to maintain.

The second priority is to fill out the API with more events for custom addons to the warfare system.

**Comment by TomLewis** [comment]
Sounds like a great idea! Is there a list somewhere that says whats in it at present? As a big movecraft user im always looking for features to give to players!

**Comment by TylerS1066** [comment]
I had moved assault and siege out of the main plugin and into this one without any edits, but because MCC wasn't yet released I was unable to test it.  Once MCC is released I'll be focusing my time on getting this released.

**Comment by TomLewis** [comment]
Brilliant, I never have been able to get the siege feature working in MoveCraft, being separate will give it a much bigger opportunity to be polished as its own idea then instead of just a random part of movecraft, im all for this!

I need to figure out how it works properly.
