### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by winnipeg21** [APDevTeam/Movecraft-Warfare#23]
https://pastebin.com/HqXEw1Kf

Getting this error on load
purpur 1158 (1.16.5)
Movecraft 8.0.0-a.2 (APDevTeam)
Java 11

**Comment by TylerS1066** [comment]
This plugin requires [Movecraft-WorldGuard](https://github.com/APDevTeam/Movecraft-WorldGuard) and [Movecraft-Repair](https://github.com/APDevTeam/Movecraft-Repair) to function.

**Comment by winnipeg21** [comment]
I have those plugins installed and running already

**Comment by TylerS1066** [comment]
> I have those plugins installed and running already

Which versions of those plugins are you running?


EDIT: OH!  v0.5.4 does not support anything but 1.10.2 to 1.12.2.  Please use [v1.a.0.](https://github.com/APDevTeam/Movecraft-Warfare/releases/tag/1.a.0)
