### ISSUE TITLE
Option to require the siege leader to be in the siege region at all times

### ISSUE THREAD

**Issue by galacticwarrior9** [APDevTeam/Movecraft-Warfare#24]
An annoying phenomenon has emerged on my server whereby those intending to take a siege region will begin a siege, sail to the nearest protected claims where they cannot be damaged, and remain there until just before the siege's end, upon which they return to the region to ensure they win.

It would be nice if there was an option to force siege leaders to have a valid craft inside the siege region at all times during siege, rather than just at the siege's end.

**Comment by TylerS1066** [comment]
On AP, tacticians say that to successfully defend a siege you must hold the siege cap with a fleet large enough to prevent any enemy from sneaking through.  Conversely, to win a siege you must hold the cap with a fleet large enough to repel any defending forces from the cap.  To assist in this, we've added rules about the minimum distance from protective regions to the cap (500-800 blocks), and we've created a "5 minute rule" which requires that the siege leader be in the cap for the last 5 minutes of the siege, in a single ship (or swapping from one flagship to another).

The eventual goal is to rebalance sieges to be more of a "King of the Hill" style of combat over the region, but that is a long ways away.

For right now the goal is to just implement a three stage system: preparation, combat, and capture.  The prep and combat stages are similar to the current ones, but the capture stage would follow and require the siege leader to be in the region (in a siege-able craft) for the entire duration.  On AP, we'd likely configure these to be 30 minutes, 25 minutes, and 5 minutes respectively.  But you could easily configure them to be 25/5/30 minutes if you wish to make it far harder (and fulfil this request).

I'm going to leave this open to track the progress on the "capture stage" of siege.
