### ISSUE TITLE
Make siege timezones configurable

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft-Warfare#5]
**Is your feature request related to a problem? Please describe.**
Currently, siege schedules are all in UTC, with no configurable options

**Describe the solution you'd like**
An option in either config.yml or sieges.yml called SiegeTimeZone should be added in order to make siege time zone configurable

**Comment by TylerS1066** [comment]
After further review, I think that adding timezones will only complicate this plugin and overall be detrimental to the codebase.
