### ISSUE TITLE
Get actual player name as siege placeholders

### ISSUE THREAD

**Issue by yash-mathur** [APDevTeam/Movecraft-Warfare#7]
Current siege placeholder (%l = Siege leaders) returns CraftPlayer{name=SiegeAttacker} rather than just an ign, in this case SiegeAttacker. Can we get another placeholder to get the IGN of player who initiated the siege?

Actual IGNs would be useful in rewarding winners for example,
_/give SiegeAttacker_ diamond. Currently this just returns _/give CraftPlayer{name=SiegeAttacker} diamond_ which doesn't work

**Comment by TylerS1066** [comment]
This is definitely a bug, Line 111 of SiegeProgressTask should refer to siegeLeader.getName() not toString()
